jwt:
  secret: 'asfksdjnfksdngkljershtjehstrkbskdnfbskadbfkasjgfjncxvmzd,mnwroehg'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountmanager
    password:
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect